---
apiVersion: v1
kind: Service
metadata:
  namespace: registry
  name: registry
  labels:
    kalexlab.xyz/app: registry
spec:
  type: ClusterIP
  ports:
    - name: registry
      port: 5000
      protocol: TCP
    - name: registry-ui
      port: 8080
      protocol: TCP
  selector:
    kalexlab.xyz/app: registry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: registry
  name: registry
  labels:
    kalexlab.xyz/app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      kalexlab.xyz/app: registry
  minReadySeconds: 5
  template:
    metadata:
      labels:
        kalexlab.xyz/app: registry
    spec:
      initContainers:
        - name: copy-nginx
          image: joxit/docker-registry-ui:2
          imagePullPolicy: Always
          command: [
              "sh",
              "-c",
              "cp -r /etc/nginx/* /mnt/nginx && \
              cp -r /usr/share/nginx/html/* /mnt/nginx-html",
            ]
          volumeMounts:
            - mountPath: /mnt/nginx
              name: nginx
            - mountPath: /mnt/nginx-html
              name: nginx-html
      restartPolicy: Always
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: Always

          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false

          ports:
            - containerPort: 5000
              protocol: TCP

          resources:
            requests:
              memory: 20Mi
              cpu: 5m
          # TODO
          #   limits:
          #     memory: 200Mi
          #     cpu: 100m

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            failureThreshold: 3
            periodSeconds: 30

          volumeMounts:
            - name: registry-pvc
              mountPath: /var/lib/registry
            - name: registry-conf
              mountPath: /etc/docker/registry
              readOnly: true

        - name: registry-ui
          image: joxit/docker-registry-ui:2
          env:
            - name: REGISTRY_TITLE
              value: "kalexlab registry"
            - name: NGINX_PROXY_PASS_URL
              value: "http://localhost:5000"
            - name: SINGLE_REGISTRY
              value: "true"
            - name: DELETE_IMAGES
              value: "true"
            - name: REGISTRY_SECURED
              value: "true"

          ports:
            - containerPort: 8080
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 3
            periodSeconds: 30

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE

          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /etc/nginx
              name: nginx
            - mountPath: /var/cache/nginx
              name: nginx-cache
            - mountPath: /usr/share/nginx/html
              name: nginx-html

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

      enableServiceLinks: false
      automountServiceAccountToken: false

      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
        - name: nginx
          emptyDir:
            sizeLimit: 1Gi
        - name: nginx-cache
          emptyDir:
            sizeLimit: 1Gi
        - name: nginx-html
          emptyDir:
            sizeLimit: 1Gi
        - name: registry-conf
          projected:
            sources:
              - configMap:
                  name: registry-conf
                  items:
                    - key: config.yml
                      path: config.yml
              - secret:
                  name: registry-htpasswd
                  items:
                    - key: htpasswd
                      path: htpasswd

  volumeClaimTemplates:
    - metadata:
        name: registry-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 10Gi
