---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scrutiny-collector-conf
  namespace: scrutiny
data:
  # TODO: wait for https://github.com/AnalogJ/scrutiny/pull/686 to be merged
  collector.yaml: |
    ---
    version: 1

    host:
      id: "hermes"

    allow_listed_devices:
      - /dev/sda
      - /dev/sdb

    log:
      level: INFO

    api:
      endpoint: "https://scrutiny.kalexlab.xyz"
