---
apiVersion: v1
kind: Secret
metadata:
  name: scrutiny-influxdb-secrets
  namespace: scrutiny
type: Opaque
data:
  DOCKER_INFLUXDB_INIT_USERNAME: "{{ scrutiny_influxdb_username | b64encode }}"
  DOCKER_INFLUXDB_INIT_PASSWORD: "{{ scrutiny_influxdb_password | b64encode }}"
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "{{ scrutiny_influxdb_token | b64encode }}"
  DOCKER_INFLUXDB_INIT_ORG: "{{ scrutiny_influxdb_org | b64encode }}"
  DOCKER_INFLUXDB_INIT_BUCKET: "{{ scrutiny_influxdb_bucket | b64encode }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: scrutiny-conf
  namespace: scrutiny
data:
  scrutiny.yaml: "{{ lookup('template', 'misc/scrutiny.yml.j2') | b64encode }}"
