---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: scrutiny
  name: collector
  labels:
    kalexlab.xyz/app: scrutiny
    kalexlab.xyz/component: collector
spec:
  replicas: 1
  serviceName: collector
  selector:
    matchLabels:
      kalexlab.xyz/app: scrutiny
      kalexlab.xyz/component: collector
  updateStrategy:
    type: RollingUpdate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        kalexlab.xyz/app: scrutiny
        kalexlab.xyz/component: collector
    spec:
      restartPolicy: Always
      containers:
        - name: collector
          image: ghcr.io/analogj/scrutiny:master-collector
          imagePullPolicy: Always

          securityContext:
            privileged: true

          volumeMounts:
            - mountPath: /opt/scrutiny/config/collector.yaml
              name: scrutiny-collector-conf

      enableServiceLinks: false
      automountServiceAccountToken: false

      volumes:
        - name: scrutiny-collector-conf
          config:
            name: scrutiny-collector-conf
