---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: scrutiny
  name: collector
  labels:
    kalexlab.xyz/app: scrutiny
    kalexlab.xyz/component: collector
spec:
  replicas: 1
  serviceName: collector
  selector:
    matchLabels:
      kalexlab.xyz/app: scrutiny
      kalexlab.xyz/component: collector
  updateStrategy:
    type: RollingUpdate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        kalexlab.xyz/app: scrutiny
        kalexlab.xyz/component: collector
    spec:
      restartPolicy: Always
      containers:
        - name: collector
          image: ghcr.io/analogj/scrutiny:master-collector
          imagePullPolicy: Always

          env:
            - name: COLLECTOR_API_ENDPOINT
              value: "https://scrutiny.kalexlab.xyz"

          securityContext:
            privileged: true

          # TODO: PR the option in scrutiny to whitelist drives
          # and use it in the configuration
          # volumeMounts:
          #   - mountPath: /opt/scrutiny/config/collector.yaml
          #     name: scrutiny-collector-conf

      enableServiceLinks: false
      automountServiceAccountToken: false

      # volumes:
      #   - name: scrutiny-collector-conf
      #     secret:
      #       secretName: scrutiny-collector-conf
