---
- name: Create ingress for Longhorn UI
  kubernetes.core.k8s:
    definition: |
      ---
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        namespace: longhorn-system
        name: longhorn-ingress
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: {{ clusterissuer }}

          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        labels:
          kalexlab.xyz/app: longhorn
      spec:
        tls:
          - hosts:
              - "longhorn.kalexlab.xyz"
            secretName: letsencrypt-tls-longhorn
        rules:
          - host: longhorn.kalexlab.xyz
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: longhorn-frontend
                      port:
                        number: 80
    state: present
