---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: media
  name: sonarr-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "{{ clusterissuer }}"

    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    kalexlab.xyz/app: media
spec:
  tls:
    - hosts:
        - "sonarr.media.kalexlab.xyz"
      secretName: letsencrypt-tls-sonarr
  rules:
    - host: sonarr.media.kalexlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
