---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: media
  name: qbittorrent-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "{{ clusterissuer }}"

    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    kalexlab.xyz/app: media
spec:
  tls:
    - hosts:
        - "torrent.media.kalexlab.xyz"
      secretName: letsencrypt-tls-qbittorrent
  rules:
    - host: torrent.media.kalexlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr-qbittorrent-gluetun
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: media
  name: prowlarr-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "{{ clusterissuer }}"

    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    kalexlab.xyz/app: media-ui
spec:
  tls:
    - hosts:
        - "prowlarr.media.kalexlab.xyz"
      secretName: letsencrypt-tls-prowlarr
  rules:
    - host: prowlarr.media.kalexlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr-qbittorrent-gluetun
                port:
                  number: 9696
