---
apiVersion: v1
kind: Service
metadata:
  namespace: homer
  name: homer
  labels:
    kalexlab.xyz/app: homer
spec:
  type: ClusterIP
  ports:
    - name: homer
      port: 8080
      protocol: TCP
  selector:
    kalexlab.xyz/app: homer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: homer
  name: homer
  labels:
    kalexlab.xyz/app: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      kalexlab.xyz/app: homer
  minReadySeconds: 5
  template:
    metadata:
      labels:
        kalexlab.xyz/app: homer
    spec:
      restartPolicy: Always

      initContainers:
        - name: copy-config-and-theme
          image: docker.io/library/alpine:3.17
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - >
              cp /mnt/config.yml /mnt/assets &&
              mkdir -p /mnt/assets/images /mnt/assets/icons &&
              wget -O /mnt/assets/catppuccin.css https://raw.githubusercontent.com/mrpbennett/catppuccin-homer/main/flavours/catppuccin-frappe.css &&
              wget -O /mnt/assets/images/romb.png https://raw.githubusercontent.com/mrpbennett/catppuccin-homer/main/assets/images/backgrounds/romb.png &&
              wget -O /mnt/assets/icons/dark_circle.png https://raw.githubusercontent.com/mrpbennett/catppuccin-homer/main/assets/logos/dark_circle.png &&
              wget -O /tmp/favicon.zip https://github.com/mrpbennett/catppuccin-homer/raw/main/assets/favicons/dark_favicon.zip && unzip -od /mnt/assets/icons /tmp/favicon.zip
          volumeMounts:
            - mountPath: /mnt/assets
              name: homer-pvc
            - mountPath: /mnt/config.yml
              name: homer-conf
              subPath: config.yml
      containers:
        - name: app
          image: b4bz/homer:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080
              protocol: TCP

          # resources:
          #   requests:
          #     memory: 5Mi
          #     cpu: 1m
          #   limits:
          #     memory: 20Mi
          #     cpu: 5m

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 3
            periodSeconds: 30

          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

          volumeMounts:
            - mountPath: /www/assets
              name: homer-pvc

      enableServiceLinks: false
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

      volumes:
        - name: homer-conf
          configMap:
            name: homer-conf

  volumeClaimTemplates:
    - metadata:
        name: homer-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 100Mi
