---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: homer
  name: homer-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "{{ clusterissuer }}"

    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    kalexlab.xyz/app: homer
spec:
  tls:
    - hosts:
        - "homer.kalexlab.xyz"
      secretName: letsencrypt-tls-homer
  rules:
    - host: homer.kalexlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homer
                port:
                  number: 8080
