---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: adguard
  name: adguard-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "{{ clusterissuer }}"

    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    kalexlab.xyz/app: adguard
spec:
  tls:
    - hosts:
        - "adguard.dns.kalexlab.xyz"
      secretName: letsencrypt-tls-adguard
  rules:
    - host: adguard.dns.kalexlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard
                port:
                  number: 80
